#!/bin/bash
#nohup java -jar Xmx128m springboot.jar --spring.profiles.active=prod &
#docker启动容器
#docker run --name mysql -d -it -p 3306:3306 -e MYSQL_ROOT_PASSWORD=123456 mysql:5.6 ‐‐character‐set‐server=utf8mb4 ‐‐collation‐server=utf8mb4_unicode_ci
#docker run -d -p 6379:6379 --name redis docker.io/redis
#flume启动agent
#nohup bin/flume-ng agent -c conf/ -f job/kafka-flume-logger.conf -n a1 &


spring:
  profiles:
    active: dev


